[package]
name = "holyballs"
version = "0.7.3"
edition = "2024"

[dependencies]
bevy = {version = "0.19.1"}
bevy_rapier3d = { version = "0.36.0" }
rand = "0.10.2"
bevy_fontmesh = {version="0.6.0"}
crossfire = "3.1.19"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
#log = "0.4.33"

[dev-dependencies]
bevy = { version = "0.19.1", features = ["debug"] }

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
lto = false
incremental = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.4.3", features = ["wasm_js"] }
wasm-bindgen = { version = "0.2.127", features = []}

[profile.release]
opt-level = 'z'     # Optimize for size
lto = true          # Enable Link Time Optimization
codegen-units = 1   # Reduce number of codegen units
panic = 'abort'     # Remove panic formatting overhead
strip = true        # Strip debug info and symbols
