name: Deploy Holyballs
run-name: Deploy-holyballs-to-wasm
on:
  push:
    branches: [ master ]

# Grant permissions required to deploy to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Optimize Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Alsa and Udev dependencies (Required for Bevy)
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libudev-dev

      - name: Install wasm32 target
        run: |
          rustup target add wasm32-unknown-unknown

      - name: Install WASM tooling
        run: |
          cargo install --force wasm-bindgen-cli
          mkdir ./binaryen
          wget -qO- https://github.com/WebAssembly/binaryen/releases/download/version_126/binaryen-version_126-arm64-macos.tar.gz | tar xvz --strip-components 1 -C ./binaryen binaryen-version_126

      - name: Build Bevy Game for WASM
        run: |
          cargo build --release --target wasm32-unknown-unknown

      - name: Generate WASM Bindings
        run: |
          wasm-bindgen --target web \
            --out-dir ./site/generated \
            target/wasm32-unknown-unknown/release/holyballs.wasm

      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
