name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Enable Caching
        uses: Swatinem/rust-cache@v2
      - name: Build Release
        run: cargo build --release
      - name: Copy assets
        run: cp -r assets/. target/release/